### ISSUE TITLE
Add option to either post to Instagram, Twitter or both

### ISSUE THREAD

**Issue by prashantsengar** [prashantsengar/RedIns#1]
Currently, it posts to both Twitter and Instagram. Add a feature to make the user choose where he wants to post and then post there only. 

A simple boolean variable can be used for this. Will have to make the code more modular.

**Comment by Kiran2115** [comment]
hey prashantsengar i would like to work on this issue.

**Comment by prashantsengar** [comment]
Sure, go ahead @Kiran2115

**Comment by Shardul555** [comment]
Hey @prashantsengar  Can you tell current status of this problem..can I also try this one..

**Comment by prashantsengar** [comment]
You can start working on it

**Comment by Shardul555** [comment]
<img width="960" alt="Screenshot 2019-12-17 19 01 59" src="https://user-images.githubusercontent.com/56973333/70999736-fa852300-20ff-11ea-957b-3027c1be3c4a.png">

**Comment by Shardul555** [comment]
can you please explain why it is not responding

**Comment by prashantsengar** [comment]
Why are you entering 1?

**Comment by Shardul555** [comment]
I take it as number of files to be  uploaded

**Comment by prashantsengar** [comment]
You don't need to do that. I guess the number is taken randomly.

**Comment by Shardul555** [comment]
Please check the pr sent and guide me further

**Comment by RhuthuHegde** [comment]
Can I work on this issue?

**Comment by prashantsengar** [comment]
@RhuthuHegde sure! please check out the code and let me know how you will be proceeding further :)
