### ISSUE TITLE
Use RedPy to download media

### ISSUE THREAD

**Issue by prashantsengar** [prashantsengar/RedIns#5]
Currently, the script accesses Reddit API directly. Instead of that I would like to use my own Reddit API wrapper [RedPy](https://github.com/prashantsengar/RedPy)

**Comment by shreyateeza** [comment]
Hey, I would like to work on this issue. Can you please guide me through it?

**Comment by prashantsengar** [comment]
@shreyateeza if you check the code for RedIns, you will find a `dload` function that is used to download the media from Reddit. What you have to do now is to create a new function to download content. The current `dload` function uses Reddit API directly to download images. You need to check out RedPy and see how to download images using that and create a new download function in RedIns to download media using RedPy.

**Comment by prashantsengar** [comment]
Hey @shreyateeza, did you have any success in this?

**Comment by sudo-gyan** [comment]
I would like to work on this. Can you assign me ?

**Comment by prashantsengar** [comment]
Sure @sudo-gyan ! Let me know how you are going to start working on this
